### ISSUE TITLE
Los campos maintainer de la entidad Dataset no aparece en data.json

### ISSUE THREAD

**Issue by poligarcia** [datosgobar/ckanext-datajsonar#20]
Los campos `maintainer` ("Mantenedor" e "Email del Mantenedor") debe aparecer asociado al dataset con el siguiente formato:

```json
"contactPoint": {
  "fn": "Poli García",
  "contactPoint": "poli[AT]devartis[DOT]com"
}
```

![image](https://user-images.githubusercontent.com/1264073/35413386-05a454ae-01fe-11e8-91c8-08d08aa8572e.png)

**Comment by poligarcia** [comment]
Logré dar con la lógica que genera entradas nuevas en el `data.json` y logré una versión que genera sl json tal cual está solicitado en el issue:

![image](https://user-images.githubusercontent.com/1264073/35459926-dc0fc75e-02c0-11e8-9956-26359c7ee8fa.png)

Sin embargo, encontré una función original de GSA/ckanext-datajson que genera el objeto `contactPoint` de manera _algo similar_:

![image](https://user-images.githubusercontent.com/1264073/35459983-0d9218a4-02c1-11e8-812d-56af68f7ca0c.png)

Si observan con atención van a notar dos diferencias:

1. El objeto `contactPoint` tiene un atributo adicional `@type`
1. El atributo `hasEmail` está prefijado con `mailto:`

Quisiera que me indiquen qué versión deseamos conservar, considerando si efectivamente vamos a hacer uso de esas diferencias.

cc @abenassi @juanehernandez

**Comment by abenassi** [comment]
Hola @poligarcia !

Nosotros no usamos los campos @type y similares de USA, no son parte del
perfil europeo ni les vemos utilidad. Sin embargo tampoco daña que estén.

El prefijo de malito:, sin embargo, no lo queremos. Me parece un uso
restrictivo que hacen del campo en USA pensado para un caso muy particular.
Debería figurar el mail sin aditamentos.

Nos quedaríamos con la primer versión.


El 26 ene. 2018 17:56, "Poli García" <notifications@github.com> escribió:

Logré dar con la lógica que genera entradas nuevas en el data.json y logré
una versión que genera sl json tal cual está solicitado en el issue:

[image: image]
<https://user-images.githubusercontent.com/1264073/35459926-dc0fc75e-02c0-11e8-9956-26359c7ee8fa.png>

Sin embargo, encontré una función original de GSA/ckanext-datajson que
genera el objeto contactPoint de manera *algo similar*:

[image: image]
<https://user-images.githubusercontent.com/1264073/35459983-0d9218a4-02c1-11e8-812d-56af68f7ca0c.png>

Si observan con atención van a notar dos diferencias:

   1. El objeto contactPoint tiene un atributo adicional @type
   2. El atributo hasEmail está prefijado con mailto:

Quisiera que me indiquen qué versión deseamos conservar, considerando si
efectivamente vamos a hacer uso de esas diferencias.

cc @abenassi <https://github.com/abenassi> @juanehernandez
<https://github.com/juanehernandez>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/datosgobar/ckanext-datajsonar/issues/20#issuecomment-360901996>,
or mute the thread
